### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by SashaCroatia** [INFO-526-S24/project-01-WackyWednesday#1]
The following is the peer review of the project proposal by Plotcrafters. The team members that participated in this review are 

- Alexander Berliner - @SashaCroatia
- Tushar Kant Singh - @ustusharkant

- Describe the goal of the project.
The goal of this project is to unveil insights on a football team's performance during the 2021-2022 Premier league season. The first question asks whether the home or away team has a significant effect on the their performance. The second question asks if it is possible to forecast the final scores of football matches based on the ratio of fouls to cards.

- Describe the data used or collected.
The dataset is from the Premier League Match Data 2021 - 2022. The variables include teams, referee, stats by home and away side including number of fouls, shots, yellow cards, red cards, and season rankings.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
Not mentioned in proposal.

- Is there anything that is unclear from the proposal?
Yes. 1) While there is a section on the description of the dataset, the goal section is missing. 2) There is no description of what approaches/methods will be used to each question.

- Provide constructive feedback on how the team might be able to improve their project.
The "Reason for Choosing this Dataset" section was clearly written by ChatGPT. We can tell because the language is exaggerated and most of the sentences provide little additional information (fluff). Please rewrite concisely in your own words.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We're most interested in knowing how you can forecast/predict the final score for each team based on the variables the dataset provides.

- Provide constructive feedback on any issues with file and/or code organization.
Overall fine, but some sections are incomplete or missing (see above for which ones).

- (Optional) Any further comments or feedback?
Please refrain from using ChatGPT to write some of your sections. Use your own writing in your project, and please be concise.

**Comment by gmcginnis** [comment]
Thank you for the feedback. Issues were addressed on 11 & 12 Feb with the following commits:
- a62356f202209b041dc6e372d0ecfb273b927379
- 6c5c6964fef6c916dafcc7f68ead11638935f237
- 895faa7446f89dcccd936692c8ae1aee9b25603f
