### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by AgastyaDeshraju** [INFO-526-S24/project-01-WackyWednesday#2]
The following is the peer review of the project proposal by "fight club". The team members that participated in this review are 

- Agastya Deshraju - @AgastyaDeshraju 
- Usama Ahmed - @usamaahmedsh
- Naitik Shah - @naitik2608
- Gorantla Sai Laasya - @Sailaasya-1
- Lakshmi Anchula - @lakshmineharika
- Divya Dhole - @Divyadhole

- **Describe the goal of the project.**
The goal of the project is to analyze soccer statistical data from the 2021-22 Premier League season. The two questions that the project is trying to answer are; 1) Whether home teams have an advantage over away teams when it comes to winning performance. 2)To forecast the result of a game based on the ratio of the fouls to cards. They also include a plan to analyze whether there is a bias against away teams when it comes to features such as fouls and the cards they receive.

- **Describe the data used or collected.**
The dataset that the team uses comes from Kaggle, and it covers the data across the 2021-22 season of the Premier League. The data contains information regarding the date of the match, the name of the home and away teams, the number of shots and goals at half-time and full-time by both the away and home teams, the number of cards and fouls by both the teams and other information such as the end result of the matches and the referees officiating the match.

- **Describe how the research question will be answered, e.g. what approaches / methods will be used.**
The authors of the project haven’t included their approach or method to the questions that they’re intending to solve.

- **Is there anything that is unclear from the proposal?**
The team has not provided question 2 in the section that it’s necessary. Although we were able to find it at the end of the document, the team’s proposal would significantly improve from shifting the question up to the section that was provided for the questions. Also, the anticipated results of the projects aren’t provided very coherently and we believe it would help with the understanding of the project, if the team provided their goals and expected outcomes.
Moreover, there might be other factors, not included in the dataset, that could affect the performance of the home team. For example, one of their top scorers might be sick or going through some issues because of which that player was not able to score more goals during that season. Their analysis does not account for how they will cater to this noise. 

- **Provide constructive feedback on how the team might be able to improve their project.**
The authors of the project could benefit a lot from having a clear and concise flow. There are a lot of parts of the proposal that are out of place or incomplete. Setting up their goals early on could help them in the future with attaining their desired outcomes.
They should increase their dataset to more than one season and take the mean of goals scored or some other estimate to truly understand whether the home team advantage exists or not.

- **What aspect of this project are you most interested in and would like to see highlighted in the presentation.**
We are most interested in seeing how the team intends to predict the end result of a match based on variables such as fouls and cards. Also, knowing whether referees have a home and away bias as well, would be an interesting revelation if proven correct.

- **Provide constructive feedback on any issues with file and/or code organization.**
The formatting of the proposal is really good, but they should try organizing the document better, and including content where it’s supposed to be. 

- **(Optional) Any further comments or feedback?**

**Comment by gmcginnis** [comment]
Thank you for the feedback. Issues were addressed on 11 & 12 Feb with the following commits:
- a62356f202209b041dc6e372d0ecfb273b927379
- 6c5c6964fef6c916dafcc7f68ead11638935f237
- 895faa7446f89dcccd936692c8ae1aee9b25603f
