### ISSUE TITLE
Proposal regrade request

### ISSUE THREAD

**Issue by gmcginnis** [INFO-526-S24/project-01-WackyWednesday#4]
Regrade / additional feedback request; changes have been made to add timeline (162f70f2fd1fe28b1edf1629512e6a3f24eedfc8), assign members (0f9c5bb30315f9060289caf15e9d8930808a3b7d, 49982c682a778384b0acc3a9711a1bab8d64dec9)

**Comment by Gchism94** [comment]
Final score is **9.25/10** (midpoint between 8.5 and 10)
